Use stub for net.LookupIP in tests.
opiproject/opi-spdk-bridge pull request #263
Opened 2023-03-17 08:22 UTC by artek-koltun

net.LookupIP takes time to get resolved, which slows down frontend test execution. Instead, a stub call which returns a predefined value can be used to get a quicker feedback from the tests.

2023-03-17 12:05 UTC, glimchb requested changes
I think better approach is to get rid of lookup at all, this was just a placeholder anyway. Listen address could be another argument to the app. We don’t want to assume where spdk container or app running and what ip we listen on…

2023-03-17 14:25 UTC, glimchb requested changes
change looks good. but it will fail CI, please add `-tcp_traddr` to docker-compose

2023-03-17 16:06 UTC, artek-koltun commented
> change looks good. but it will fail CI, please add `-tcp_traddr` to docker-compose

Thank you for pointing this out

2023-03-20 11:06 UTC, artek-koltun commented
`golangci` is failing on main as well due to the update to 1.52.0

2023-03-20 11:22 UTC, artek-koltun commented
> `golangci` is failing on main as well due to the update to 1.52.0

Fix to pass golangci is in https://github.com/opiproject/opi-spdk-bridge/pull/269

2023-03-20 14:15 UTC, glimchb commented on pkg/frontend/nvme.go
> +	result.ListenAddress.Traddr = c.listenAddr.String()
if we make `tcp_traddr` in a form of `127.0.0.1:4444` then we can also change the port number.

could be a new issue to the backlog to change in a separate PR

2023-03-20 14:17 UTC, glimchb approved these changes
lgtm. opened #270 to track an improvement

2023-03-20 14:17 UTC, merged