[storage] Renaming Aio and Null to Volume
opiproject/opi-spdk-bridge pull request #559
Opened 2023-07-25 21:55 UTC by glimchb

This brings more consistency to the naming of backend

See opiproject/opi-api#304

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

2023-07-25 22:17 UTC, glimchb commented
See https://github.com/opiproject/opi-api/issues/304

2023-07-27 07:38 UTC, artek-koltun requested changes

2023-07-27 07:38 UTC, artek-koltun commented on pkg/backend/null.go
> +// DeleteNullVolume deletes a Null Debug instance
deletes a Null volume

2023-07-27 07:38 UTC, artek-koltun commented on pkg/backend/null.go
> +// NullVolumeStats gets a Null Debug instance stats
gets a Null volume stats

2023-07-27 07:38 UTC, artek-koltun commented on pkg/backend/null.go
> +// GetNullVolume gets a a Null Debug instance
gets a a Null volume

2023-07-27 07:38 UTC, artek-koltun commented on pkg/backend/null.go
> +// UpdateNullVolume updates a Null Debug instance
updates a Null volume

2023-07-27 14:59 UTC, artek-koltun approved these changes
LGTM

2023-07-27 15:07 UTC, merged