feat: add otel grpc for monitoring
opiproject/opi-spdk-bridge pull request #683
Opened 2023-09-29 21:20 UTC by glimchb

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

2023-09-30 13:04 UTC, glimchb commented
Need to use: `grpc_middleware.ChainUnaryServer`

2023-10-02 22:25 UTC, glimchb commented on cmd/main.go
> +		otelgrpc.UnaryServerInterceptor(),
not enough
need also to create `tracing.TracerProvider`

2023-10-04 14:55 UTC, artek-koltun requested changes
To prevent merging. Want to review it tomorrow

2023-10-05 06:33 UTC, artek-koltun approved these changes

2023-10-05 06:33 UTC, merged