feat(frontend): any as spdk params for nvme controller
opiproject/opi-spdk-bridge pull request #797
Opened 2023-11-14 11:52 UTC by artek-koltun

This is needed if any other bridge needs to pass its own parameters as a part of nvmf_subsystem_add_listener call.

2023-11-14 14:57 UTC, glimchb requested changes
I want to avoid use of `any`
let's discuss

2023-11-15 07:13 UTC, artek-koltun commented
> I want to avoid use of `any` let's discuss

We already use any with virtio-blk transport, and I want to be consistent. However, let's consider alternatives:
* return `map[string]any` instead of `NvmfSubsystemAddListenerParams`
    * embed `map[string]any` into `NvmfSubsystemAddListenerParams` is not supported by the language
* embed any into struct. Does not work. We do not get a flatten json structure with an interface.
* move rpc call into transport instead of returning params struct.

What is your suggestions/ideas?

2023-11-15 18:37 UTC, glimchb commented
I remember we already discussed option to move rpc call into transport instead of returning params struct... 

WDYT ?

2023-11-16 06:47 UTC, artek-koltun commented
> I remember we already discussed option to move rpc call into transport instead of returning params struct...
> 
> WDYT ?

It is the third option in my list above 😄

> * move rpc call into transport instead of returning params struct.

In general, I agree that we can proceed that way

2023-11-17 09:51 UTC, artek-koltun commented
Closing. The calls to spdk will be moved into the transports

2023-11-17 09:51 UTC, closed without merging